backend_url: "https://bgp.core01.eu/api/ingest.php"
api_key: "bgpdoctor_api_key"
interval_seconds: 60
hostname: "egde01" // hihi edging
asn: 213413
birdc_path: "/usr/sbin/birdc"
pathvector_config: "/etc/pathvector.yml"
ping_targets:
  - "1.1.1.1"
  - "2606:4700:4700::1111"